SELECT * FROM customer_data LIMIT 10;

--Q1. What is the total revenue generated by male vs. female customers?

select gender, SUM(purchase_amount) as revenue
from customer_data 
group by gender

--Q2. Which customers used a discount but still spent more than the average purchase amount? 

select customer_id, purchase_amount
from customer_data 
where discount_applied= 'Yes'and purchase_amount >= (select AVG(purchase_amount) FROM customer_data)


-- Q3. Which are the top 5 products with the highest average review rating?

select item_purchased , round(AVG(review_rating::numeric),2) as "Average Review Rating"
from customer_data cd
group by item_purchased 
order by AVG(review_rating) desc
limit 5

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 

select shipping_type, round(AVG(purchase_amount),2)
from customer_data cd 
where shipping_type in ('Express', 'Free Shipping')
group by shipping_type


--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.

select subscription_status,
	COUNT(customer_id) AS "total_customers",
	round(AVG(purchase_amount),2) as Average_puchase_Amount,
	SUM(purchase_amount) as Total_Revenue
from customer_data cd 
group by subscription_status 

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?


SELECT item_purchased,
       count(item_purchased ) AS total,
       ROUND(SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END),2) AS discount_rate,
       ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_percentage
FROM customer_data
GROUP BY item_purchased
ORDER BY discount_percentage  DESC
LIMIT 5;

--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 

with customer_type as (
select (
case 
	when previous_purchases=1 then 'new'
	when previous_purchases between 1 and 10 then 'returning'
	else 'loyal'
end) as customer_segment
from customer_data)

select customer_segment, count(*) as "Number of Customers"
from customer_type
group by customer_segment

--Q8. What are the top 3 most purchased products within each category? 

WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer_data
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?


select 
count(customer_id) as repeat_buyers,
SUM(case when subscription_status='Yes' then 1 else 0 end ) as subscribed_customers,
ROUND(
        SUM(CASE WHEN subscription_status = 'Yes' THEN 1 ELSE 0 END) * 100.0 
        / COUNT(customer_id),
        2
    ) AS percentage
from customer_data cd 
where cd.previous_purchases > 5

--another version of the same question


SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM customer_data
WHERE previous_purchases > 5
GROUP BY subscription_status;


--Q10. What is the revenue contribution of each age group? 

-- already there is agegroup, just need to calculate the revenue and sort it in decending 

select age_group,
SUM(purchase_amount) as revenue
from customer_data cd 
group by age_group
order by revenue DESC

